# Dockerfile para o backend
FROM node:18-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend .
# Gera o Prisma Client
RUN npx prisma generate
EXPOSE 3001
CMD ["npm", "run", "dev"] 